

export const FETCH_ALL_USERS_BLOGS_REQUEST = 'FETCH_ALL_USERS_BLOGS_REQUEST';
export const FETCH_ALL_USERS_BLOGS_SUCCESS = 'FETCH_ALL_USERS_BLOGS_SUCCESS';
export const FETCH_ALL_USERS_BLOGS_FAIL = 'FETCH_ALL_USERS_BLOGS_FAIL';

export const GET_ALL_BLOGS_REQUEST = 'GET_ALL_BLOGS_REQUEST'
export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS'
export const GET_ALL_BLOGS_FAIL = 'GET_ALL_BLOGS_FAIL'

export const DELETE_BLOG_REQUEST = 'DELETE_BLOGS_REQUEST'
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOGS_SUCCESS'
export const DELETE_BLOG_FAIL = 'DELETE_BLOGS_FAIL'

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL';

export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAIL = 'CREATE_BLOG_FAIL';